version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: shop_backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: shop_frontend
    volumes:
      - /app/node_modules
      - /app/build
      - ./frontend:/app
    env_file:
      -  ./frontend/.env.prod
    depends_on:
      - backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    container_name: shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
