version: '3.8'

services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: shop_backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
